services:
  - type: web
    name: 26AS_PARSER_TOOL
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -c gunicorn.conf.py --worker-tmp-dir /dev/shm"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
